****COGNIFYZ INTERNSHIP MACHINE LEARNING INTERN****

****TASK 2: RESTAURANT RECOMMENDATION****

STEP 1: Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

STEP:2 Load Dataset

In [3]:
df = pd.read_csv("/kaggle/input/datasets/soumyasahoo23/restrruant-data/Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

STEP 3: Preprocess Data

In [4]:
df.fillna('', inplace=True)

# Clean column names
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()

# Create combined feature column
df['combined_features'] = df['cuisines'].astype(str) + " " + df['price range'].astype(str)

STEP 4: Vectorize Text Data

In [5]:
vectorizer = TfidfVectorizer()
feature_matrix = vectorizer.fit_transform(df['combined_features'])

STEP 5: Recommendation Function

In [6]:
def recommend_restaurants(user_cuisine, user_price_range, top_n=5):
    
    
    user_input = f"{user_cuisine} {user_price_range}"
    user_vector = vectorizer.transform([user_input])
    similarities = cosine_similarity(user_vector, feature_matrix).flatten()
    similar_indices = similarities.argsort()[-top_n:][::-1]
    recommended = df.iloc[similar_indices][['restaurant name', 'cuisines', 'price range', 'aggregate rating']]
    
    return recommended

STEP 6: Test Recommendation

In [7]:
user_cuisine = "Italian"
user_price_range = "2"

recommend_restaurants(user_cuisine, user_price_range)

     restaurant name cuisines  price range  aggregate rating
1106   Da Pizza Zone  Italian            2               0.0
31      Villa Tevere  Italian            4               4.1
3603         Foodies  Italian            1               0.0
9344       San Carlo  Italian            3               4.2
3219  28 Capri Italy  Italian            3               3.9